block_2:
  position: [-5.0, 0.0, 1.5]
  orientation: [0.0, 0.0, 0.0]

block_3:
  position: [-5.0, 0.0, 2.5]
  orientation: [0.0, 0.0, 0.0]

block_4:
  position: [-5.0, 0.0, 3.5]
  orientation: [0.0, 0.0, 0.0]

block_5:
  position: [-5.0, 0.0, 4.5]
  orientation: [0.0, 0.0, 0.0]
