block_2:
  position: [5.0, 0.0, 0.5]
  orientation: [0.0, 0.0, 0.0]

block_3:
  position: [5.0, 3.0, 0.5]
  orientation: [0.0, 0.0, 0.0]

block_4:
  position: [5.0, 5.0, 0.5]
  orientation: [0.0, 0.0, 0.0]

block_5:
  position: [0.0, 0.0, 0.5]
  orientation: [0.0, 0.0, 0.0]