block_2:
  position: [0.0, 0.0, 0.5]
  orientation: [0.0, 0.0, 0.0]

block_3:
  position: [0.0, 0.0, 1.5]
  orientation: [0.0, 0.0, 0.0]

block_4:
  position: [0.0, 0.0, 2.5]
  orientation: [0.0, 0.0, 0.0]

block_5:
  position: [0.0, 0.0, 3.5]
  orientation: [0.0, 0.0, 0.0]

block_6:
  position: [0.0, 0.0, 4.5]
  orientation: [0.0, 0.0, 0.0]

block_7:
  position: [0.0, 0.0, 5.5]
  orientation: [0.0, 0.0, 0.0]

block_8:
  position: [0.0, 0.0, 6.5]
  orientation: [0.0, 0.0, 0.0]

block_9:
  position: [0.0, 0.0, 7.5]
  orientation: [0.0, 0.0, 0.0]

block_10:
  position: [0.0, 0.0, 8.5]
  orientation: [0.0, 0.0, 0.0]