block_1:
  type: "static"
  position: [-5.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 0.0, 0.0]
  size: 1.0

block_2:
  type: "dynamic"
  position: [-5.0, 0.0, 1.0]
  orientation: [0.0, 0.0, 0.0]
  color: [1.0, 0.0, 0.0]
  size: 1.0

block_3:
  type: "dynamic"
  position: [-5.0, 0.0, 2.0]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 1.0, 0.0]
  size: 1.0

block_4:
  type: "dynamic"
  position: [-5.0, 0.0, 3.0]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 0.0, 1.0]
  size: 1.0

block_5:
  type: "dynamic"
  position: [-5.0, 0.0, 4.0]
  orientation: [0.0, 0.0, 0.0]
  color: [1.0, 1.0, 0.0]
  size: 1.0

block_6:
  type: "dynamic"
  position: [-10.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 0.0, 0.0]
  size: 1.0

block_7:
  type: "dynamic"
  position: [-10.0, 0.0, 1.0]
  orientation: [0.0, 0.0, 0.0]
  color: [1.0, 0.0, 0.0]
  size: 1.0

block_8:
  type: "dynamic"
  position: [-10.0, 0.0, 2.0]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 1.0, 0.0]
  size: 1.0

block_9:
  type: "dynamic"
  position: [5.0, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0]
  color: [0.0, 0.0, 1.0]
  size: 1.0

block_10:
  type: "dynamic"
  position: [5.0, 0.0, 1.0]
  orientation: [0.0, 0.0, 0.0]
  color: [1.0, 1.0, 0.0]
  size: 1.0

block_11:
  type: "dynamic"
  position: [5.0, 0.0, 2.0]
  orientation: [0.0, 0.0, 0.0]
  color: [1.0, 1.0, 0.0]
  size: 1.0

robot:
  type: "robot"
  position: [-3.0, -3.0, 0.0]
  orientation: [0.0, 0.0, 0.0]