(define (problem blocks_problem_5)
    (:domain blocks)
    (:objects block_2 block_3 block_4 block_5 - dynamic gnd p1 p10 p2 p3 p4 p5 p6 p7 p8 p9 - location robot - robot block_1 - static)
    (:init (above p1 gnd) (above p10 p9) (above p2 gnd) (above p3 p2) (above p4 gnd) (above p5 p4) (above p6 gnd) (above p7 p1) (above p8 p7) (above p9 p8) (at block_1 p1) (at block_2 p2) (at block_3 p3) (at block_4 p4) (at block_5 p5) (at robot p6) (at-top block_1) (at-top block_3) (at-top block_5) (clear p10) (clear p7) (clear p8) (clear p9) (gripper-empty) (is-ground gnd) (on block_3 block_2) (on block_5 block_4))
    (:goal (and (at block_2 p7) (at block_3 p8) (at block_4 p9) (at block_5 p10) (on block_5 block_4) (on block_4 block_3) (on block_3 block_2) (on block_2 block_1)))
)